/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface SpiCandidat {}
  interface SpiCandidatAttributes extends StencilHTMLAttributes {}

  interface SpiEnseignant {}
  interface SpiEnseignantAttributes extends StencilHTMLAttributes {}

  interface SpiFormationAdd {
    'history': RouterHistory;
  }
  interface SpiFormationAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiFormationDetail {
    'componentWillLoad': () => Promise<void>;
    'match': MatchResults;
  }
  interface SpiFormationDetailAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface SpiFormation {
    'history': RouterHistory;
  }
  interface SpiFormationAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiPromotion {}
  interface SpiPromotionAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SpiCandidat': Components.SpiCandidat;
    'SpiEnseignant': Components.SpiEnseignant;
    'SpiFormationAdd': Components.SpiFormationAdd;
    'SpiFormationDetail': Components.SpiFormationDetail;
    'SpiFormation': Components.SpiFormation;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiPromotion': Components.SpiPromotion;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'spi-candidat': Components.SpiCandidatAttributes;
    'spi-enseignant': Components.SpiEnseignantAttributes;
    'spi-formation-add': Components.SpiFormationAddAttributes;
    'spi-formation-detail': Components.SpiFormationDetailAttributes;
    'spi-formation': Components.SpiFormationAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-promotion': Components.SpiPromotionAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLSpiCandidatElement extends Components.SpiCandidat, HTMLStencilElement {}
  var HTMLSpiCandidatElement: {
    prototype: HTMLSpiCandidatElement;
    new (): HTMLSpiCandidatElement;
  };

  interface HTMLSpiEnseignantElement extends Components.SpiEnseignant, HTMLStencilElement {}
  var HTMLSpiEnseignantElement: {
    prototype: HTMLSpiEnseignantElement;
    new (): HTMLSpiEnseignantElement;
  };

  interface HTMLSpiFormationAddElement extends Components.SpiFormationAdd, HTMLStencilElement {}
  var HTMLSpiFormationAddElement: {
    prototype: HTMLSpiFormationAddElement;
    new (): HTMLSpiFormationAddElement;
  };

  interface HTMLSpiFormationDetailElement extends Components.SpiFormationDetail, HTMLStencilElement {}
  var HTMLSpiFormationDetailElement: {
    prototype: HTMLSpiFormationDetailElement;
    new (): HTMLSpiFormationDetailElement;
  };

  interface HTMLSpiFormationElement extends Components.SpiFormation, HTMLStencilElement {}
  var HTMLSpiFormationElement: {
    prototype: HTMLSpiFormationElement;
    new (): HTMLSpiFormationElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiPromotionElement extends Components.SpiPromotion, HTMLStencilElement {}
  var HTMLSpiPromotionElement: {
    prototype: HTMLSpiPromotionElement;
    new (): HTMLSpiPromotionElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'spi-candidat': HTMLSpiCandidatElement
    'spi-enseignant': HTMLSpiEnseignantElement
    'spi-formation-add': HTMLSpiFormationAddElement
    'spi-formation-detail': HTMLSpiFormationDetailElement
    'spi-formation': HTMLSpiFormationElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-promotion': HTMLSpiPromotionElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'spi-candidat': HTMLSpiCandidatElement;
    'spi-enseignant': HTMLSpiEnseignantElement;
    'spi-formation-add': HTMLSpiFormationAddElement;
    'spi-formation-detail': HTMLSpiFormationDetailElement;
    'spi-formation': HTMLSpiFormationElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-promotion': HTMLSpiPromotionElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
